# Constants for the application

STATUS_NEW = "NEW"
STATUS_PICKING = "PICKING"
STATUS_PACKING = "PACKING"
STATUS_STAGED = "STAGED"
STATUS_SHIPPED = "SHIPPED"
STATUS_BLOCKED = "BLOCKED"
STATUS_CANCELLED = "CANCELLED"

PRIORITY_NORMAL = "NORMAL"
PRIORITY_URGENT = "PRIORITY"

WAREHOUSE_MAIN = "MAIN"
WAREHOUSE_BACKUP = "BACKUP"

EXCEPTION_TYPES = [
    "INVENTORY_MISMATCH",
    "OUT_OF_STOCK",
    "WRONG_VARIANT",
    "PACKAGE_MISSING",
    "COURIER_DELAY",
    "MISSED_PICKUP",
    "OTHER"
]

SEVERITY_LOW = "LOW"
SEVERITY_MEDIUM = "MEDIUM"
SEVERITY_HIGH = "HIGH"

EXCEPTION_STATUS_OPEN = "OPEN"
EXCEPTION_STATUS_RESOLVED = "RESOLVED"

TRANSFER_REQUESTED = "REQUESTED"
TRANSFER_IN_TRANSIT = "IN_TRANSIT"
TRANSFER_COMPLETED = "COMPLETED"
